name: Build Sphinx Lite Image

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Set Docker Build Version
        id: version
        run: |
          echo "CONTAINER_VERSION=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: authsec/sphinx-lite:$CONTAINER_VERSION
