name: Build Sphinx-Lite Docker Image

on:
  push:
    branches: 
      - '*'
      - '!main'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Set Docker Build Versions
        id: version
        run: |
          full_docker_version=${GITHUB_REF#refs/heads/}
          major_version=$(echo $full_docker_version | cut -d '.' -f 1)
          echo "DOCKER_VERSION=${full_docker_version}" >> $GITHUB_ENV
          echo "DOCKER_MAJOR_VERSION=${major_version}" >> $GITHUB_ENV

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            authsec/sphinx-lite:${{ env.DOCKER_VERSION }}
            authsec/sphinx-lite:${{ env.DOCKER_VERSION }}.${{ github.run_number }}
            authsec/sphinx-lite:${{ env.DOCKER_MAJOR_VERSION }}
            authsec/sphinx-lite:latest
